---

os: osx
osx_image: xcode9.2
language: objective-c

before_install:
  # Uninstall existing Homebrew installation.
  - 'echo "y\n" | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"'

install:
  - sudo easy_install pip
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory
  - which brew
  - brew help

  # Run the playbook a second time to ensure that it's idempotent.
  - PLAYBOOK_OUTPUT=$(mktemp)
  - ansible-playbook tests/test.yml -i tests/inventory | tee ${PLAYBOOK_OUTPUT}
  - >
      cat ${PLAYBOOK_OUTPUT}
      | grep -A 1 'PLAY RECAP'
      | grep -q 'ok=.*changed=0.*unreachable=0.*failed=0'
      && (echo 'Playbook is idempotent' && exit 0)
      || (echo 'Playbook is NOT idempotent' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
