---
- name: create directories
  file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0775
  become: true
  with_items:
    - Cellar
    - Homebrew
    - Frameworks
    - bin
    - etc
    - include
    - lib
    - opt
    - sbin
    - share
    - var

- name: create directories (zsh refuses to read from these directories if group writable)
  file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0755
  become: true
  with_items:
    - share/zsh
    - share/zsh/site-functions

- name: create cache directory
  file:
    path: "{{ homebrew_cache_dir }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0775
  become: true

- name: register whether the Command Line Tools have been installed
  shell: /usr/bin/xcode-select -print-path 2>/dev/null
  register: clt_installed
  become: true
  ignore_errors: yes
  changed_when: false

- block:
  - name: touch temporary file, {{ clt_placeholder_file }}, that enables the 'softwareupdate' utility to list the Command Line Tools
    file:
      path: "{{ clt_placeholder_file }}"
      state: touch

  - name: search for latest version of Command Line Tools
    shell: softwareupdate -l | grep -E '^ *\* Command Line Tools' | sed 's/^ *\* //' | tail -n 1
    register: clt_version

  - name: install Command Line Tools - {{ clt_version.stdout }}
    command: /usr/sbin/softwareupdate -i '{{ clt_version.stdout }}'

  - name: set active developer directory
    command: /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools

  always:
    - name: remove temporary file
      file:
        path: "{{ clt_placeholder_file }}"
        state: absent
  become: true
  when: clt_installed.stdout == ""

- name: clone {{ brew_git_repo }}
  git:
    repo: "{{ brew_git_repo }}"
    dest: "{{ homebrew_repo_dir }}"
    update: no

- name: link brew binary
  file:
    src: "{{ homebrew_repo_dir }}/bin/brew"
    dest: "{{ homebrew_prefix }}/bin/brew"
    state: link

- name: run brew update to complete installation
  command: "{{ homebrew_prefix }}/bin/brew update --force"
  environment:
    HOMEBREW_NO_ANALYTICS_THIS_RUN: "1"
    HOMEBREW_NO_ANALYTICS_MESSAGE_OUTPUT: "1"

- name: turn off analytics
  command: "{{ homebrew_prefix }}/bin/brew analytics off"
